# Generated by Django 3.1.4 on 2020-12-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='searchStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sRollno', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sName', models.CharField(max_length=20)),
                ('sBranch', models.CharField(max_length=3)),
                ('sCourse', models.CharField(max_length=10)),
                ('sRollno', models.CharField(max_length=10)),
                ('sYear', models.IntegerField(max_length=1)),
                ('sAddress', models.CharField(max_length=15)),
            ],
        ),
    ]
